library(shiny)
library(shinyjs)

fluidPage(
  useShinyjs(),
  titlePanel("Remote Asthma Monitoring App"), 
  fluidRow(column(width = 8, offset = 2, 
                  h4("Please answer all questions as accurately as possible. 
                     Each of these questions is based on monitoring of your child's asthma
                     symptoms and severity over the past two weeks. After you submit, 
                     your child's asthma control level and future monitoring plan will be
                     provided below. If your child is having trouble talking, walking, 
                     or his/her fingers or lips are blue, 
                     call 911."))), 
  fluidRow(column(width = 8, offset = 2, 
                  dateInput("date", "Please enter today's date:"))),
  fluidRow(column(width = 8, offset = 2, 
                  textInput("email", "Please enter your email address:"))),
  # fluidRow(column(width = 8, offset = 2, 
  #                 selectInput("numeric_day", "In the last two weeks, 
  #                 how many days did your child have asthma symptoms, 
  #                 such as wheezing, coughing, or tightness in the chest?", 
  #                 0, min = 0, max = 14, value = 0, width = '100%'))),
  # fluidRow(column(width = 8, offset = 2, 
  #                 sliderInput("numeric_d_albuterol", "In the last two weeks, 
  #                 how many days has your child used either an albuterol inhaler, 
  #                 albuterol nebulizer, or any combination of the two?", 
  #                 0, min = 0, max = 14, value = 0, width = '100%'))),
  # fluidRow(column(width = 8, offset = 2, 
  #                 sliderInput("numeric_night", "In the last two weeks, 
  #                 how many times did your child wake up at night due to coughing, 
  #                 wheezing, shortness of breath, or tightness of chest?", 
  #                 0, min = 0, max = 14, value = 0, width = '100%'))),
  # fluidRow(column(width = 8, offset = 2, 
  #                 sliderInput("numeric_n_albuterol", "In the last two weeks, 
  #                 how many nights has your child used either an albuterol inhaler, 
  #                 albuterol nebulizer, or any combination of the two?", 
  #                 0, min = 0, max = 14, value = 0, width = '100%'))), 
  fluidRow(column(width = 8, offset = 2, 
                  selectInput("numeric_day", "In the last two weeks, 
                              how many days did your child have asthma symptoms, 
                              such as wheezing, coughing, or tightness in the chest?", 
                              choices = 0:14, width = '100%'))),
  fluidRow(column(width = 8, offset = 2, 
                  selectInput("numeric_d_albuterol", "In the last two weeks, 
                              how many days has your child used either an albuterol inhaler, 
                              albuterol nebulizer, or any combination of the two?", 
                              choices = 0:14, width = '100%'))),
  fluidRow(column(width = 8, offset = 2, 
                  selectInput("numeric_night", "In the last two weeks, 
                              how many times did your child wake up at night due to coughing,
                              wheezing, shortness of breath, or tightness of chest?", 
                              choices = 0:14, width = '100%'))),
  fluidRow(column(width = 8, offset = 2, 
                  selectInput("numeric_n_albuterol", "In the last two weeks, 
                              how many nights has your child used either an albuterol inhaler, 
                              albuterol nebulizer, or any combination of the two?", 
                              choices = 0:14, width = '100%'))), 
  fluidRow(column(width = 8, offset = 2,       
                  actionButton("submit", "Submit"))), 
  br(), 
  fluidRow(column(width = 8, offset = 2,   
                  h3(hidden(textOutput("header1"))))),
  fluidRow(column(width = 8, offset = 2,   
                  hidden(textOutput("report")))),
  br(),
  fluidRow(column(width = 8, offset = 2,   
                  h3(hidden(textOutput("header2"))))),
  fluidRow(column(width = 8, offset = 2,
                  hidden(textOutput("plan")))), 
  br(), 
  br(), 
  br()
) 